# Generated by Django 6.0.4 on 2026-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=100)),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=8)),
                ('joining_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
